import { expandToStringWithNL, Model } from "../../../../../models/model.js";
import fs from "fs"
import path from "path";
import {getEntityName} from "../../../../../../util/generator-utils.js";

export function generate(model: Model, target_folder: string) : void {
    fs.writeFileSync(path.join(target_folder,`IBaseSecurityRepository.cs`), generateBaseSecurity(model))
    fs.writeFileSync(path.join(target_folder,`IRoleRepository.cs`), generateRoleRepository(model))
    fs.writeFileSync(path.join(target_folder,`IUserRepository.cs`), generateUserRepository(model))
    
}

function generateUserRepository(model: Model): string {
    return expandToStringWithNL`

/* 
@generated by leds-tools-spark
@layer repository
@entity User    
*/

using ${model.configuration?.name}.Domain.Security.Account.Entities;

namespace ${model.configuration?.name}.Domain.Interfaces.Security
{

    public interface IUserRepository : IBaseSecurityRepository<User>
    {
        /*
         @generated by leds-tools-spark
         @operation get
         @entity User
         @param email string
         @param cancellationToken CancellationToken
         @return User
         */
        Task<User?> GetUserByEmailAsync(string email, CancellationToken cancellationToken);
        /*
         @generated by leds-tools-spark
         @operation get
         @entity User
         @param code string
         @param cancellationToken CancellationToken
         @return User
         */
        Task<User?> GetUserByCode(string code, CancellationToken cancellationToken);
        /*
         @generated by leds-tools-spark
         @operation get
         @entity User
         @param code string
         @param cancellationToken CancellationToken
         @return User   
         */
        Task<User?> GetUserByPasswordCode(string code, CancellationToken cancellationToken);
        /*
         @generated by leds-tools-spark
         @operation get
         @entity User
         @param refreshToken Guid
         @param cancellationToken CancellationToken
         @return User
         */
        public Task<User?> GetUserByRefreshCode(Guid refreshToken, CancellationToken cancellationToken);
        /*
         @generated by leds-tools-spark
         @operation exists
         @entity User
         @param email string
         @param cancelationToken CancellationToken
         @return bool
         */
        Task<bool> AnyAsync(string email, CancellationToken cancelationToken);
    }
}
`
}

function generateRoleRepository(model: Model): string {
    return expandToStringWithNL`
using ${model.configuration?.name}.Domain.Security.Account.Entities;

/*
 @generated by leds-tools-spark
 @layer repository
 @entity Role
 */
namespace ${model.configuration?.name}.Domain.Interfaces.Security
{   
    /*
     @generated by leds-tools-spark
     @operation get
     @entity Role
     @param name string
     @param cancelationToken CancellationToken
     @return Role
     */
    public interface IRoleRepository : IBaseSecurityRepository<Role>
    {
        Task<Role> GetRoleByName(string name, CancellationToken cancelationToken);
    }
}
`
}

function generateBaseSecurity(model: Model): string {
    return expandToStringWithNL`
using ${model.configuration?.name}.Domain.Security.Shared.Entities;

/* 
@generated by leds-tools-spark
@layer domain
@entity BaseSecurity
 */
namespace ${model.configuration?.name}.Domain.Interfaces.Security
{
    public interface IBaseSecurityRepository<T> where T : Entity
    {
        /*
        @generated by leds-tools-spark
        @operation create
        @entity BaseSecurity
        @param entity T
        */
        void Create(T entity);
        /*
         @generated by leds-tools-spark
         @operation update
         @entity BaseSecurity
         @param entity T
         */
        void Update(T entity);
        /*
         @generated by leds-tools-spark
         @operation delete
         @entity BaseSecurity
         @param entity T
         */
        void Delete(T entity);
        /*
         @generated by leds-tools-spark
         @operation getById
         @entity BaseSecurity
         @param id Guid
         @return IQueryable<T>
         */
        IQueryable<T> GetById(Guid id);
        /*
         @generated by leds-tools-spark
         @operation getAll
         @entity BaseSecurity
         @return IQueryable<T>
         */
        IQueryable<T> GetAll();
    }
}
`
}