import { expandToString } from "../../../../../../models/model.js";
import { Model } from "../../../../../../models/model.js";
import fs from "fs";
import path from "path";

export function generate(model: Model, target_folder: string): void {
    fs.writeFileSync(path.join(target_folder, "Response.cs"), generateResponse(model));
}
function getEntityName(model: Model): string {
    const name = model.configuration?.name || "";
    return name.startsWith("Cadastro") ? name.replace("Cadastro", "") : name;
}

function generateResponse(model: Model): string {
    return expandToString`
using Flunt.Notifications;

/*
 * @generated by leds-tools-spark
 * @layer application
 * @entity Response
 */

namespace ${model.configuration?.name}.Application.Shared.UseCases
{
    public abstract class Response
    {
        /*
        * @generated by leds-tools-spark
        * @entity Response
        * @operation base-response
        * @return Response
        */
        public string Message { get; set; } = string.Empty;
        public int Status { get; set; } = 400;
        public bool IsSuccess => Status is >= 200 and <= 299;
        public IEnumerable<Notification>? Notifications { get; set; }
    }
}`;
}