import path from "path"
import { Model, expandToStringWithNL } from "../../../../../models/model.js"
import fs from "fs"

export function generate(model: Model, target_folder: string) : void {

    fs.writeFileSync(path.join(target_folder, `BaseSecurityRepository.cs`), generateBaseSecurity(model))
    fs.writeFileSync(path.join(target_folder, `RoleRepository.cs`), generateRoleRepository(model))
    fs.writeFileSync(path.join(target_folder, `UserRepository.cs`), generateUserRepository(model))
}

function generateBaseSecurity(model: Model) : string {
    return expandToStringWithNL`
using ${model.configuration?.name}.Domain.Interfaces.Security;
using ${model.configuration?.name}.Domain.Security.Shared.Entities;
using ${model.configuration?.name}.Infrastructure.Context;

namespace ${model.configuration?.name}.Infrastructure.Security.Repositories
{
    /*
    @generated by leds-tools-spark
    @layer infrastructure
    @entity BaseSecurityRepository
    */
    public class BaseSecurityRepository<T> : IBaseSecurityRepository<T> where T : Entity
    {
        protected readonly AppDbContext Context;

        /*
        @generated by leds-tools-spark
        @operation constructor
        @entity BaseSecurityRepository
        @param context AppDbContext
        */
        public BaseSecurityRepository(AppDbContext context)
        {
            Context = context;
        }

        /*
        @generated by leds-tools-spark
        @operation create
        @entity BaseSecurityRepository
        @param entity T
        */
        public void Create(T entity)
        {
            Context.Add(entity);
        }
        /*
        @generated by leds-tools-spark
        @operation update
        @entity BaseSecurityRepository
        @param entity T
        */
        public void Update(T entity)
        {
            Context.Update(entity);
        }
        /*
        @generated by leds-tools-spark
        @operation delete
        @entity BaseSecurityRepository
        @param entity T
        */
        public void Delete(T entity)
        {
            Context.Remove(entity);
        }
        /*
        @generated by leds-tools-spark
        @operation getById
        @entity BaseSecurityRepository
        @param id Guid
        @return IQueryable<T>
        */
        public IQueryable<T> GetById(Guid id)
        {
            return Context.Set<T>().Where(x => x.Id == id).AsQueryable();
        }

        /*
        @generated by leds-tools-spark
        @operation getAll
        @entity BaseSecurityRepository
        @return IQueryable<T>
        */
        public IQueryable<T> GetAll()
        {
            return Context.Set<T>().ToList().AsQueryable();
        }
    }
}`
}

function generateRoleRepository(model: Model) : string {
    return expandToStringWithNL`
using Microsoft.EntityFrameworkCore;
using ${model.configuration?.name}.Domain.Interfaces.Security;
using ${model.configuration?.name}.Domain.Security.Account.Entities;
using ${model.configuration?.name}.Infrastructure.Context;

namespace ${model.configuration?.name}.Infrastructure.Security.Repositories
{
    /* 
    @generated by leds-tools-spark
    @layer infrastructure
    @entity RoleRepository
    */
    public class RoleRepository : BaseSecurityRepository<Role>, IRoleRepository
    {
        private readonly AppDbContext _context;
        /*
        @generated by leds-tools-spark
        @operation constructor
        @entity RoleRepository
        @param context AppDbContext
        */
        public RoleRepository(AppDbContext context) : base(context)
        {
            _context = context;
        }

        /*
        @generated by leds-tools-spark
        @operation getRoleByName
        @entity RoleRepository
        @param name string
        @param cancelationToken CancellationToken
        @return Task<Role>
        */
        public Task<Role> GetRoleByName(string name, CancellationToken cancelationToken)
        {
            return _context.Roles.FirstOrDefaultAsync(x => x.Name == name, cancellationToken: cancelationToken);
        }
    }
}`
}

function generateUserRepository(model : Model) : string {
    return expandToStringWithNL`
using Microsoft.EntityFrameworkCore;
using ${model.configuration?.name}.Domain.Interfaces.Security;
using ${model.configuration?.name}.Domain.Security.Account.Entities;
using ${model.configuration?.name}.Infrastructure.Context;

namespace ${model.configuration?.name}.Infrastructure.Security.Repositories
{
    /*
    @generated by leds-tools-spark
    @layer infrastructure
    @entity UserRepository
    */
    public class UserRepository : BaseSecurityRepository<User>, IUserRepository
    {
        private readonly AppDbContext _context;
        /*
        @generated by leds-tools-spark
        @operation constructor
        @entity UserRepository
        @param context AppDbContext
        */
        public UserRepository(AppDbContext context) : base(context)
        {
            _context = context;
        }
        /*
        @generated by leds-tools-spark
        @operation anyAsync
        @entity UserRepository
        @param email string
        @param cancelationToken CancellationToken
        @return Task<bool>
        */
        public Task<bool> AnyAsync(string email, CancellationToken cancelationToken)
        {
            return
                _context.Users
                        .AsNoTracking()
                        .AnyAsync(x => x.Email.Address == email);
        }

        /*
        @generated by leds-tools-spark
        @operation getUserByCode
        @entity UserRepository
        @param code string
        @param cancellationToken CancellationToken
        @return Task<User?>
        */
        public Task<User?> GetUserByCode(string code, CancellationToken cancellationToken)
        {
            return _context.Users
                        .Include(x => x.Roles)
                        .FirstOrDefaultAsync(x => x.Email.Verification.Code == code, cancellationToken: cancellationToken);
        }

        /*
        @generated by leds-tools-spark
        @operation getUserByEmailAsync
        @entity UserRepository
        @param email string
        @param cancellationToken CancellationToken
        @return Task<User?>
        */

        public Task<User?> GetUserByEmailAsync(string email, CancellationToken cancellationToken)
        {
            return _context.Users
                        .Include(x => x.Roles)
                        .FirstOrDefaultAsync(x => x.Email.Address == email);
        }
        /*
        @generated by leds-tools-spark
        @operation getUserByPasswordCode
        @entity UserRepository
        @param code string
        @param cancellationToken CancellationToken
        @return Task<User?>
        */
        public Task<User?> GetUserByPasswordCode(string code, CancellationToken cancellationToken)
        {
            return _context.Users
                        .Include(x => x.Roles)
                        .FirstOrDefaultAsync(x => x.Password.ResetCode == code, cancellationToken: cancellationToken);
        }
        /*
        @generated by leds-tools-spark
        @operation getUserByRefreshCode
        @entity UserRepository
        @param refreshToken Guid
        @param cancellationToken CancellationToken
        @return Task<User?>
        */
        public Task<User?> GetUserByRefreshCode(Guid refreshToken, CancellationToken cancellationToken)
        {
            return _context.Users
                        .Include(x => x.Roles)
                        .FirstOrDefaultAsync(x => x.RefreshToken == refreshToken, cancellationToken: cancellationToken);
        }
    }
}`
}