import { expandToStringWithNL, Model } from "../../../../../../models/model.js";
import fs from "fs";
import path from "path";

export function generate(model: Model, target_folder: string): void {
    fs.writeFileSync(path.join(target_folder, `User.cs`), generateUser(model));
    fs.writeFileSync(path.join(target_folder, `Role.cs`), generateRole(model));
}

function generateUser(model: Model): string {
    return expandToStringWithNL`
using ${model.configuration?.name}.Domain.Security.Account.ValueObjects;
using ${model.configuration?.name}.Domain.Security.Shared.Entities;

namespace ${model.configuration?.name}.Domain.Security.Account.Entities
{
    /*
    * @generated by leds-tools-spark
    * @layer model
    * @entity User
    */
    public class User : Entity
    {
        public string Name { get; private set; } = string.Empty;
        public Email Email { get; private set; } = null!;
        public Password Password { get; private set; } = null!;
        public List<Role> Roles { get; set; } = [];
        public Guid? RefreshToken { get; set; }

        /*
        @generated by leds-tools-spark
        @operation constructor
        @entity User
        */
        protected User() { }

        /*
        @generated by leds-tools-spark
        @operation constructor
        @entity User
        @param name string
        @param email Email
        @param password Password
        @param refreshToken Guid?
        */
        public User(string name, Email email, Password password, Guid? refreshToken)
        {
            Name = name;
            Email = email;
            Password = password;
            RefreshToken = refreshToken;
            Roles = new List<Role>();
        }

        /*
        @generated by leds-tools-spark
        @operation constructor
        @entity User
        @param name string
        @param email Email
        @param password Password
        */

        public User(string name, Email email, Password password)
        {
            Name = name;
            Email = email;
            Password = password;
            Roles = new List<Role>();
        }

        /*
        @generated by leds-tools-spark
        @operation update-password
        @entity User
        @param plainTextPassword string
        @param code string
        */

        public void UpdatePassword(string plainTextPassword, string code)
        {
            if (!string.Equals(code.Trim(), Password.ResetCode.Trim(), StringComparison.CurrentCultureIgnoreCase))
                throw new Exception("Código de restauração inválido");

            var password = new Password(plainTextPassword);
            Password = password;
        }

        /*
        @generated by leds-tools-spark
        @operation update-email
        @entity User
        @param email Email
        */

        public void UpdateEmail(Email email)
        {
            Email = email;
        }

        /*
        @generated by leds-tools-spark
        @operation update-refresh-token
        @entity User
        @param token Guid?
        */
        public void UpdateRefreshToken(Guid? token)
        {
            RefreshToken = token;
        }
            
        /*
        @generated by leds-tools-spark
        @operation add-role
        @entity User
        @param role Role
        */
        public void addRole(Role role)
        {
            Roles.Add(role);
        }
    }
}`;
}

function generateRole(model: Model): string {
    return expandToStringWithNL`
using ${model.configuration?.name}.Domain.Security.Shared.Entities;

namespace ${model.configuration?.name}.Domain.Security.Account.Entities
{
    /*
    * @generated by leds-tools-spark
    * @layer model
    * @entity Role
    */
    public class Role : Entity
    {
        public string Name { get; set; } = string.Empty;
        public List<User> Users { get; set; } = new();

        /*
        @generated by leds-tools-spark
        @operation constructor
        @entity Role
        @param name string
        */
       
        public Role(string name)
        {
            Name = name;
        }
    }
}`;
}