import { expandToStringWithNL, Model } from "../../../../../models/model.js";
import fs from "fs";
import path from "path";
import {getEntityName} from "../../../../../../util/generator-utils.js";
export function generate(model: Model, target_folder: string) : void {
    fs.writeFileSync(path.join(target_folder, "BaseSecurityService.cs"),generateBaseSecurity(model))
    fs.writeFileSync(path.join(target_folder, "EmailService.cs"),generateEmailService(model))
}

function generateBaseSecurity(model: Model) : string {
    return expandToStringWithNL`
using MediatR;
using ${model.configuration?.name}.Domain.Interfaces.Security;
using ${model.configuration?.name}.Domain.Security.Shared.Entities;

namespace ${model.configuration?.name}.Application.Security.Services
{
    /*
     * @generated by leds-tools-spark
     * @layer service
     * @entity BaseSecurityEntity
     */
    public class BaseSecurityService<Repository> : IBaseSecurityRepository<Entity>
        where Repository : IBaseSecurityRepository<Entity>
    {
        

        private readonly IMediator _mediator;
        private readonly Repository _repository;

        public BaseSecurityService(IMediator mediator, Repository repository)
        {
            /*
            * @generated by leds-tools-spark
            * @operation constructor
            * @param mediator IMediator
            * @param repository Repository
            */
            _mediator = mediator;
            _repository = repository;
        }

        public void Create(Entity entity)
        {
            /*
            * @generated by leds-tools-spark
            * @operation create
            */
            throw new NotImplementedException();
        }

        public void Delete(Entity entity)
        {
            /*
            * @generated by leds-tools-spark
            * @operation delete   
            */
            throw new NotImplementedException();
        }

        public IQueryable<Entity> GetAll()
        {
            /*
            * @generated by leds-tools-spark
            * @operation get-all
            * @return IQueryable<Entity>
            */
            throw new NotImplementedException();
        }

        public IQueryable<Entity> GetById(Guid id)
        {
            /*
            * @generated by leds-tools-spark
            * @operation get-by-id
            * @param id Guid
            * @return IQueryable<Entity>
            */
            throw new NotImplementedException();
        }

        public void Update(Entity entity)
        {
            /**
            * @generated by leds-tools-spark
            * @operation update
            */
            throw new NotImplementedException();
        }
    }
}`
}

function generateEmailService(model: Model) : string {
    return expandToStringWithNL`
using MimeKit;
using ${model.configuration?.name}.Application.Security.Interfaces;
using ${model.configuration?.name}.Domain.Security.Account;
using ${model.configuration?.name}.Domain.Security.Account.Entities;
using SmtpClient = MailKit.Net.Smtp.SmtpClient;

namespace ${model.configuration?.name}.Application.Security.Services
{
    /*
    @generated by leds-tools-spark
    @layer service
    @entity Email
    */
    public class EmailService : IService
    {
        /*
        @generated by leds-tools-spark
        @operation send-verification-email
        @layer service
        @entity User
        @param user User
        @param cancellationToken CancellationToken
        @return Task
        @description Cria e envia um e-mail contendo o código de verificação de conta para o usuário.
        */
        public async Task SendVerificationEmailAsync(User user, CancellationToken cancellationToken)
        {
            var email = new MimeMessage();

            email.From.Add(new MailboxAddress("Sender Name", Configuration.Email.DefaultFromEmail));
            email.To.Add(new MailboxAddress("Receiver Name", user.Email.Address));

            email.Subject = "Verifique sua conta";
            email.Body = new TextPart(MimeKit.Text.TextFormat.Text)
            {
                Text = $"Código de verificação de email: {user.Email.Verification.Code}"
            };

            using (var smtp = new SmtpClient())
            {
                smtp.Connect("smtp.gmail.com", 587, false);

                // Note: only needed if the SMTP server requires authentication
                smtp.Authenticate(Configuration.Email.DefaultFromEmail, Configuration.Email.ApiKey);

                smtp.Send(email);
                smtp.Disconnect(true);
            }

        }

        /*
        @generated by leds-tools-spark
        @operation send-reset-password-email
        @layer service
        @entity User
        @param user User
        @param cancellationToken CancellationToken
        @return Task
        @description Cria e envia um e-mail contendo o código para alteração/reset de senha do usuário.
        */
        public async Task SendResetPasswordAsync(User user, CancellationToken cancellationToken)
        {
            var email = new MimeMessage();

            email.From.Add(new MailboxAddress("Sender Name", Configuration.Email.DefaultFromEmail));
            email.To.Add(new MailboxAddress("Receiver Name", user.Email.Address));

            email.Subject = "Alterar Senha";
            email.Body = new TextPart(MimeKit.Text.TextFormat.Text)
            {
                Text = $"Código de alteração de senha: {user.Password.ResetCode}"
            };

            using (var smtp = new SmtpClient())
            {
                smtp.Connect("smtp.gmail.com", 587, false);

                // Note: only needed if the SMTP server requires authentication
                smtp.Authenticate(Configuration.Email.DefaultFromEmail, Configuration.Email.ApiKey);

                smtp.Send(email);
                smtp.Disconnect(true);
            }

        }
    }
}`
}