import { expandToStringWithNL, Model }from "../../../../../../models/model.js"
import fs from "fs";
import path from "path";

export function generate(model: Model, target_folder: string): void {
    fs.writeFileSync(path.join(target_folder, `Entity.cs`), generateEntity(model));
}

function generateEntity(model: Model): string {
    return expandToStringWithNL`
namespace ${model.configuration?.name}.Domain.Security.Shared.Entities
{
    /*
    @generated by leds-tools-spark
    @layer model
    @entity Entity
    */
    public abstract class Entity : IEquatable<Guid>
    {
        public Guid Id { get; }
        protected Entity() => Id = Guid.NewGuid();

        /*
        @generated by leds-tools-spark
        @operation equals
        @entity Entity
        @param other Guid
        @return bool
        */
        public bool Equals(Guid id) => Id == id;

        /*@generated by leds-tools-spark
        @operation get-hash-code
        @entity Entity
        @return int
        */
        public override int GetHashCode() => Id.GetHashCode();
    }
}`;
}