import path from "path"
import { Model } from "../../../../models/model.js"
import fs from "fs"
import { expandToStringWithNL } from "../../../../models/model.js"
export function generate(model: Model, target_folder: string) : void {

    fs.writeFileSync(path.join(target_folder, `BaseEntity.cs`), generateBaseEntity(model))

}

function generateBaseEntity(model : Model) : string {
    return expandToStringWithNL`
﻿using System.Reflection;

/*
@generated by leds-tools-spark
@layer domain
@entity BaseEntity
@operation base-entity
*/

namespace ${model.configuration?.name}.Domain.Common
{

    public class BaseEntity
    {
        /*
        @generated by leds-tools-spark
        @entity BaseEntity
        */
        public Guid Id { get; set; }
        public DateTimeOffset DateCreated { get; set; }
        public DateTimeOffset? DateUpdated { get; set; }
        public DateTimeOffset? DateDeleted { get; set; }

        public void Create()
        {
            /*
            @generated by leds-tools-spark
            @operation create
            */
            this.DateCreated = DateTime.Now;
        }

        public void Update(BaseEntity entity)
        {
            /*
            @generated by leds-tools-spark
            @operation update
            @param entity BaseEntity
            */
            foreach (PropertyInfo property in entity.GetType().GetProperties())
            {
                if (property.CanWrite && property.Name != nameof(Id) && property.Name != nameof(DateCreated))
                {
                    property.SetValue(this, property.GetValue(entity));
                }
            }

            this.DateUpdated = DateTime.Now;
        }

        public void Delete()
        {
            /*
            @generated by leds-tools-spark
            @operation delete
            */
            this.DateDeleted = DateTime.Now;
        }
    }
}`
}