import { expandToString, LocalEntity, Model } from "../../../../../../models/model.js";
import fs from "fs"
import path from "path";
import { RelationInfo } from "../../../../../../models/model.js";

export function generate(model: Model, target_folder: string, cls: LocalEntity, relations: RelationInfo[]) : void {
    fs.writeFileSync(path.join(target_folder,`GetAll${cls.name}Handler.cs`), generateHandler(model, cls))
    fs.writeFileSync(path.join(target_folder,`GetAll${cls.name}Command.cs`), generateCommand(model, cls, relations))
    fs.writeFileSync(path.join(target_folder,`GetAll${cls.name}Validator.cs`), generateValidator(model, cls))
}

function getEntityName(model: Model): string {
    const name = model.configuration?.name || "";
    return name.startsWith("Cadastro") ? name.replace("Cadastro", "") : name;
}

function generateHandler (model: Model, cls: LocalEntity): string {
    return expandToString`
using ${model.configuration?.name}.Application.DTOs.Entities.Request;
using ${model.configuration?.name}.Application.DTOs.Entities.Response;
using ${model.configuration?.name}.Application.Interfaces.Entities;
using ${model.configuration?.name}.Application.UseCase.BaseCase;
using ${model.configuration?.name}.Domain.Entities;

namespace ${model.configuration?.name}.Application.UseCase.Entities.${cls.name}Case.GetAll
{
    /*
     @generated by leds-tools-spark
     @layer application
     @entity ${cls.name}
     @operation get-all
     */

    public class GetAll${cls.name}Handler : GetAllHandler<I${cls.name}Service, GetAll${cls.name}Command, ${cls.name}RequestDTO, ${cls.name}ResponseDTO, ${cls.name}>
    {
        /*
         @generated by leds-tools-spark
         @entity ${getEntityName(model)}
         @operation get-all
         @param service I${cls.name}Service 
         */

        public GetAll${cls.name}Handler(I${cls.name}Service service) : base(service)
        {
        }
    }
}`
}

function generateValidator (model: Model, cls: LocalEntity): string {
    return expandToString`
using FluentValidation;

namespace ${model.configuration?.name}.Application.UseCase.Entities.${cls.name}Case.GetAll
{
    /*
     * @generated by leds-tools-spark
     * @layer application
     * @entity ${cls.name}
     * @operation validate
     */

    public class GetAll${cls.name}Validator : AbstractValidator<GetAll${cls.name}Command>
    {
        public GetAll${cls.name}Validator()
        {
        }
    }
}
`
}

function generateCommand (model: Model, cls: LocalEntity, relations : RelationInfo[]): string {
    return expandToString`
using ${model.configuration?.name}.Application.DTOs.Entities.Response;
using MediatR;

namespace ${model.configuration?.name}.Application.UseCase.Entities.${cls.name}Case.GetAll
{
    /*
     @generated by leds-tools-spark
     @layer application
     @entity ${cls.name}
     @operation get-all
     */
    public record GetAll${cls.name}Command() : IRequest<IQueryable<${cls.name}ResponseDTO>>;
}
`
}