import { expandToStringWithNL, Model } from "../../../../../models/model.js"
import fs from "fs";
import path from "path";
export function generate(model: Model, target_folder: string) : void {
    fs.writeFileSync(path.join(target_folder, "IService.cs"),genrateIservice(model))
}

function getEntityName(model: Model): string {
    const name = model.configuration?.name || "";
    return name.startsWith("Cadastro") ? name.replace("Cadastro", "") : name;
}

function genrateIservice(model: Model) : string {
    return expandToStringWithNL`
using ${model.configuration?.name}.Domain.Security.Account.Entities;

namespace ${model.configuration?.name}.Application.Security.Interfaces
{
    /*
     * @generated by leds-tools-spark
     * @layer service
     * @entity ${getEntityName(model)}
     */
    public interface IService
    {
        Task SendVerificationEmailAsync(User user, CancellationToken cancellationToken);
        /*
         * @generated by leds-tools-spark
         * @operation send-verification-email
         * @param user User
         * @param cancellationToken CancellationToken
         * @return Task
         */
        Task SendResetPasswordAsync(User user, CancellationToken cancellationToken);
        /*
         * @generated by leds-tools-spark
         * @operation send-reset-password-email
         * @param user User
         * @param cancellationToken CancellationToken
         * @return Task
         */
    }
}`
}