import { expandToStringWithNL, Model } from "../../../../models/model.js";
import fs from "fs";
import path from "path";

export function generate(model: Model, target_folder: string) : void {

    fs.writeFileSync(path.join(target_folder, "TestHelper.cs"), generateProjectsln(model))

}

function generateProjectsln(model: Model) : string {
    return expandToStringWithNL`
using AutoFixture;
using AutoFixture.Kernel;
using ${model?.configuration?.name}.Domain.Entities;

namespace ${model?.configuration?.name}.Domain.Test.Helpers
{
    /*
    @generated by leds-tools-spark
    @layer domain-test
    @entity TestHelper
    */
    internal static class TestHelper
    {

        /*
        @generated by leds-tools-spark
        @operation get-fixture
        @entity TestHelper
        @return Fixture
        */
        public static Fixture GetFixture()
        {

            Fixture entityfixture = new Fixture();

            // Remove the ThrowingRecursionBehavior
            entityfixture.Behaviors.OfType<ThrowingRecursionBehavior>().ToList()
                .ForEach(b => entityfixture.Behaviors.Remove(b));

            // Add the OmitOnRecursionBehavior
            entityfixture.Behaviors.Add(new OmitOnRecursionBehavior());

            return entityfixture;

        }

    }
}
`
}