import { expandToStringWithNL, Model } from "../../../../../models/model.js"
import fs from "fs"
import path from "path"
import {getEntityName} from "../../../../../../util/generator-utils.js";

export function generate(model: Model, target_folder: string) : void {
    
    fs.writeFileSync(path.join(target_folder,`ValidationBehavior.cs`), generateValidationBehavior(model))
}


function generateValidationBehavior (model: Model): string {
    return expandToStringWithNL`
using FluentValidation;
using MediatR;
/*
@generated by leds-tools-spark
@layer shared-aplication
@entity Pipeline
 */
namespace ${model.configuration?.name}.Application.Shared.Behavior
{
    /*
     @generated by leds-tools-spark
     @operation pipeline-validation
     @param TRequest IRequest
     @param TResponse generic
     @return TResponse
     */
    public sealed class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse> where TRequest : IRequest<TResponse>
    {
        private readonly IEnumerable<IValidator<TRequest>> _validators;

        /*
         @generated by leds-tools-spark
         @layer infrastructure
         @operation constructor
         @param validators IEnumerable<IValidator<TRequest>>
         */
        public ValidationBehavior(IEnumerable<IValidator<TRequest>> validators)
        {
            _validators = validators;
        }

        /*
        @generated by leds-tools-spark
        @layer infrastructure
        @operation handle
        @param request TRequest
        @param next RequestHandlerDelegate<TResponse>
        @return TResponse
        */
        public async Task<TResponse> Handle(TRequest request,
                                     RequestHandlerDelegate<TResponse> next,
                                     CancellationToken cancellationToken)
        {
            if (!_validators.Any()) return await next();

            var context = new ValidationContext<TRequest>(request);

            if (_validators.Any())
            {
                context = new ValidationContext<TRequest>(request);

                var validationResults = await Task.WhenAll(_validators.Select(v => v.ValidateAsync(context, cancellationToken)));

                var failures = validationResults.SelectMany(r => r.Errors).Where(f => f != null).ToList();

                if (failures.Count != 0)
                    throw new FluentValidation.ValidationException(failures);
            }

            return await next();
        }
    }
}`
}