import { expandToStringWithNL, LocalEntity, Model, isLocalEntity, isModule } from "../../../../models/model.js";
import fs from "fs";
import path from "path";

export function generate(model: Model, target_folder: string) : void {
    
    const common_folder = target_folder + '/Common'
    const entities_folder = target_folder + '/Entities'


    fs.mkdirSync(common_folder, {recursive: true})
    fs.mkdirSync(entities_folder, {recursive: true})

    fs.writeFileSync(path.join(common_folder, `BaseRepository.cs`), generateBase(model))
    fs.writeFileSync(path.join(common_folder, `UnitOfWork.cs`), generateUnitOfWork(model))
    const modules =  model.abstractElements.filter(isModule);
  
    for(const mod of modules) {
        for(const cls of mod.elements.filter(isLocalEntity)) {
            fs.writeFileSync(path.join(entities_folder,`${cls.name}Repository.cs`), generateEntityRepository(model, cls))
        }
    }
}

function generateBase (model: Model): string {
    return expandToStringWithNL`
using ${model.configuration?.name}.Domain.Common;
using ${model.configuration?.name}.Domain.Interfaces.Common;
using ${model.configuration?.name}.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;

namespace ${model.configuration?.name}.Infrastructure.Repositories.Common
{
    /*
    @generated by leds-tools-spark
    @layer infrastructure
    @entity BaseRepository
    */

    public class BaseRepository<T> : IBaseRepository<T> where T : BaseEntity
    {
        protected readonly AppDbContext Context;
        protected readonly DbSet<T> DbSet;

        /*
        @generated by leds-tools-spark
        @operation constructor
        @entity BaseRepository
        @param context AppDbContext
        */
        public BaseRepository(AppDbContext context)
        {
            Context = context;
            DbSet =  Context.Set<T>();
        }

        /*
        @generated by leds-tools-spark
        @operation create
        @entity BaseRepository
        @param entity T
        */
        public async Task Create(T entity)
        {
            await Context.AddAsync(entity);
        }

        /*
        @generated by leds-tools-spark
        @operation delete
        @entity BaseRepository
        @param entity T
        */

        public async Task Delete(T entity)
        {
            entity.Delete();
            await Task.Run(() => Context.Remove(entity), new CancellationToken());
        }

        /*
        @generated by leds-tools-spark
        @operation update
        @entity BaseRepository
        @param entity T
        */

        public async Task Update(T entity)
        {
            await Task.Run(() => Context.Update(entity), new CancellationToken());
        }

        /*
        @generated by leds-tools-spark
        @operation getAll
        @entity BaseRepository
        @return IQueryable<T>
        */
        public IQueryable<T> GetAll()
        {
            return Context.Set<T>()
                 .AsSplitQuery().AsQueryable();
        }

        /*
        @generated by leds-tools-spark
        @operation getById
        @entity BaseRepository
        @param id Guid
        @return IQueryable<T>
        */

        public IQueryable<T> GetById(Guid id)
        {
            return Context.Set<T>().Where(x => x.Id == id).AsNoTracking().AsQueryable();
        }

        /*
        @generated by leds-tools-spark
        @operation any
        @entity BaseRepository
        @param id Guid
        @return bool
        */

        public async Task<bool> Any(Guid id)
        {
            return await Context.Set<T>().AnyAsync(x => x.Id.Equals(id));
        }

        /*
        @generated by leds-tools-spark
        @operation deleteRange
        @entity BaseRepository
        @param entities ICollection<T>
        */
        public void DeleteRange(ICollection<T> entities)
        {
            Context.Set<T>().RemoveRange(entities);
        }

        /*
        @generated by leds-tools-spark
        @operation addRange
        @entity BaseRepository
        @param entities ICollection<T>
        */

        public void AddRange(ICollection<T> entities)
        {
            Context.Set<T>().AddRange(entities);
        }
    }
}`
}

function generateUnitOfWork(model: Model) : string {
    return expandToStringWithNL`
using ${model.configuration?.name}.Domain.Interfaces.Common;
using ${model.configuration?.name}.Infrastructure.Context;

namespace ${model.configuration?.name}.Infrastructure.Repositories
{
    /*
    @generated by leds-tools-spark
    @layer repository
    @entity UnitOfWork
    */
    public class UnitOfWork : IUnitOfWork
    {
        private readonly AppDbContext _context;

        /*
        @generated by leds-tools-spark
        @operation constructor
        @entity UnitOfWork
        @param context AppDbContext
        */
        public UnitOfWork(AppDbContext context)
        {
            _context = context;
        }

        /*
        @generated by leds-tools-spark
        @operation commit
        @param cancellationToken CancellationToken
        @entity UnitOfWork
        @return Task
        */
        public async Task Commit(CancellationToken cancellationToken)
        {
            await _context.SaveChangesAsync(cancellationToken);
        }
    }
}
`
}

function generateEntityRepository(model: Model, cls: LocalEntity): string {
    return expandToStringWithNL`
﻿using ${model.configuration?.name}.Domain.Entities;
using ${model.configuration?.name}.Domain.Enums;
using ${model.configuration?.name}.Domain.Interfaces.Entities;
using ${model.configuration?.name}.Infrastructure.Context;
using ${model.configuration?.name}.Infrastructure.Repositories.Common;
using Microsoft.EntityFrameworkCore;

namespace ${model.configuration?.name}.Infrastructure.Repositories.Entities
{
    /*
    @generated by leds-tools-spark
    @layer infrastructure
    @entity ${cls.name}Repository
    */
    public class ${cls.name}Repository : BaseRepository<${cls.name}>, I${cls.name}Repository
    {
        /*
        @generated by leds-tools-spark
        @operation constructor
        @entity ${cls.name}Repository
        @param context AppDbContext
        */
       
        public ${cls.name}Repository(AppDbContext context) : base(context) { }

    }
}`
}

