import { expandToString, EnumX } from "../../../models/model.js";

export function generateEnum(enumx: EnumX, package_name: string) : string {
  

  return expandToString`
  /*
    @generated by leds-tools-spark
    @layer model  
    @entity Enum ${enumx.name}
  */
    public enum ${enumx.name} {
        ${enumx.attributes.map(a => `${a.name.toUpperCase()}` ).join(",\n")}
    }
  `;
}