import { expandToString, isLocalEntity, isModule, Model } from "../../../../models/model.js";

export function generateODataExtension(model: Model): string{
    return expandToString`
using ${model.configuration?.name}.Application.DTOs.Entities.Response;
using Microsoft.AspNetCore.OData;
using Microsoft.OData.Edm;
using Microsoft.OData.ModelBuilder;

namespace ${model.configuration?.name}.WebApi.Extensions
{
     /*
     @generated by leds-tools-spark
     @layer configuration
     @entity OData
     */

    public static class ODataExtension
    {
        /*
         @generated by leds-tools-spark
         @operation build-edm-model
         @entity OData
         @return IEdmModel
         */
        private static IEdmModel GetEdmModel()
        {
            ODataConventionModelBuilder builder = new();
            ${generateEntitySets(model)}
            return builder.GetEdmModel();
        }

        /*
         @generated by leds-tools-spark
         @operation configure-odata
         @entity OData
        */
        public static void ODataConfiguration(this IServiceCollection services)
        {
            services.AddControllers(options =>
            {
                // Add filter exceptions here
            })
            .AddOData(options => options
                .SkipToken()
                .AddRouteComponents("api", GetEdmModel())
                .Select()
                .Filter()
                .OrderBy()
                .SetMaxTop(4)
                .Count()
                .Expand());
        }
    }
}`
}

function generateEntitySets(model: Model) : string {
  
    const modules =  model.abstractElements.filter(isModule);
    let entitySets = "";
    
    for(const mod of modules) {
        for(const cls of mod.elements.filter(isLocalEntity)) {
            entitySets += `builder.EntitySet<${cls.name}ResponseDTO>("${cls.name.toLowerCase()}"); \n`
        }
    }

    return entitySets;
  
}