import { expandToString, Model } from "../../../../models/model.js";
import fs from "fs";
import path from "path";
import { generateODataExtension } from "./generateODataExtension.js";

export function generate(model: Model, target_folder: string) : void {

    fs.writeFileSync(path.join(target_folder, "AccountContextExtension.cs"), generateAccountContext(model))
    fs.writeFileSync(path.join(target_folder, "BuilderExtension.cs"), generateBuilderExtension(model))
    fs.writeFileSync(path.join(target_folder, "ClaimsPrincipalExtension.cs"), generateClaimsPrincipalExtension(model))
    fs.writeFileSync(path.join(target_folder, "ConfigureCorsPolicy.cs"), generateCorsPolicyExtension(model))
    fs.writeFileSync(path.join(target_folder, "JwtExtension.cs"), generateJwtExtension(model))
    fs.writeFileSync(path.join(target_folder, "ODataExtension.cs"), generateODataExtension(model))

}

function generateAccountContext(model: Model): string {
    return expandToString`
using MediatR;
using Microsoft.AspNetCore.Mvc;
using RequestAuth = ${model.configuration?.name}.Application.Security.Account.UseCases.Authenticate.Request;
using RequestChangePassword = ${model.configuration?.name}.Application.Security.Account.UseCases.ChangePassword.Request;
using RequestRefreshToken = ${model.configuration?.name}.Application.Security.Account.UseCases.RefreshToken.Request;
using RequestResetPasswordCode = ${model.configuration?.name}.Application.Security.Account.UseCases.SendResetPassword.Request;
using RequestSaveRefreshToken = ${model.configuration?.name}.Application.Security.Account.UseCases.SaveRefreshToken.Request;
using RequestToken = ${model.configuration?.name}.Application.Security.Account.UseCases.Verify.Request;
using RequestUser = ${model.configuration?.name}.Application.Security.Account.UseCases.Create.Request;
using ResponseAuth = ${model.configuration?.name}.Application.Security.Account.UseCases.Authenticate.Response;
using ResponseChangePassword = ${model.configuration?.name}.Application.Security.Account.UseCases.ChangePassword.Response;
using ResponseResetPasswordCode = ${model.configuration?.name}.Application.Security.Account.UseCases.SendResetPassword.Response;
using ResponseSaveRefreshToken = ${model.configuration?.name}.Application.Security.Account.UseCases.SaveRefreshToken.Response;
using ResponseUser = ${model.configuration?.name}.Application.Security.Account.UseCases.Create.Response;

namespace ${model.configuration?.name}.WebApi.Extensions
{
    /*
    @generated by leds-tools-spark
    @layer controller
    @entity Account
    */      
    public static class AccountContextExtension
    {
        // Registra os endpoints
        /*
         @generated by leds-tools-spark
         @operation register-endpoints
         @entity Account
         */
        public static void MapAccountEndpoints(this WebApplication app)
        {
            #region Create
            /*
            @generated by leds-tools-spark
            @operation create
            @entity User
            @param request RequestUser
            @return ResponseUser
            */
            app.MapPost("api/users", async ([FromBody] RequestUser request, IRequestHandler<RequestUser, ResponseUser> handler) =>
            {
                var result = await handler.Handle(request, new CancellationToken());
                return result.IsSuccess
                    ? Results.Created($"api/users/{result.Data?.id}", result)
                    : Results.Json(result, statusCode: result.Status);
            });
            #endregion
            #region Authenticate
            /*
            @generated by leds-tools-spark
            @operation authenticate
            @entity User
            @param request RequestAuth
            @return ResponseAuth
            */
            app.MapPost("api/authenticate", async ([FromBody] RequestAuth request, IRequestHandler<RequestAuth, ResponseAuth> handler,
                 IRequestHandler<RequestSaveRefreshToken, ResponseSaveRefreshToken> handlerRefreshToken) =>
            {
                var result = await handler.Handle(request, new CancellationToken());
                if (!result.IsSuccess)
                    return Results.Json(result, statusCode: result.Status);

                if (result.Data is null)
                    return Results.Json(result, statusCode: 500);

                result.Data.Token = JwtExtension.Generate(result.Data);
                result.Data.RefreshToken = JwtExtension.GenerateRefreshToken();
                result.Data.TokenExpires = DateTime.UtcNow.AddMinutes(110);

                var requestRefreshToken = new RequestSaveRefreshToken(result.Data.Id, result.Data.RefreshToken);
                handlerRefreshToken.Handle(requestRefreshToken, new CancellationToken());

                return Results.Ok(result);
            });
            #endregion

            #region Validate Token
            /*
            @generated by leds-tools-spark
            @operation validate-token
            @entity User
            @param request RequestToken
            @return ResponseAuth
            */
            app.MapPost("api/validate", async ([FromBody] RequestToken request, IRequestHandler<RequestToken, ResponseAuth> handler) =>
            {
                var result = await handler.Handle(request, new CancellationToken());
                if (!result.IsSuccess)
                    return Results.Json(result, statusCode: result.Status);

                if (result.Data is null)
                    return Results.Json(result, statusCode: 500);

                result.Data.Token = JwtExtension.Generate(result.Data);
                return Results.Ok(result);
            });
            #endregion

            #region Refresh Token
            /*
            @generated by leds-tools-spark
            @operation refresh-token
            @entity User
            @param request RequestRefreshToken
            @return ResponseAuth
            */
            app.MapPost("api/refresh", async ([FromBody] RequestRefreshToken request, IRequestHandler<RequestRefreshToken, ResponseAuth> handler,
                IRequestHandler<RequestSaveRefreshToken, ResponseSaveRefreshToken> handlerRefreshToken) =>
            {
                var result = await handler.Handle(request, new CancellationToken());
                if (!result.IsSuccess)
                    return Results.Json(result, statusCode: result.Status);

                if (result.Data is null)
                    return Results.Json(result, statusCode: 500);

                result.Data.Token = JwtExtension.Generate(result.Data);
                result.Data.RefreshToken = JwtExtension.GenerateRefreshToken();
                result.Data.TokenExpires = DateTime.UtcNow.AddMinutes(110);

                var requestRefreshToken = new RequestSaveRefreshToken(result.Data.Id, result.Data.RefreshToken);
                handlerRefreshToken.Handle(requestRefreshToken, new CancellationToken());

                return Results.Ok(result);
            });
            #endregion

            #region Request Reset Password
            /*
            @generated by leds-tools-spark
            @operation request-reset-password
            @entity User
            @param request RequestResetPasswordCode
            @return ResponseResetPasswordCode
                */
            app.MapPost("api/reset/password", async ([FromBody] RequestResetPasswordCode request, IRequestHandler<RequestResetPasswordCode, ResponseResetPasswordCode> handler) =>
            {
                var result = await handler.Handle(request, new CancellationToken());
                return Results.Ok(result);
            });
            #endregion

            #region Change Password
            /*
            @generated by leds-tools-spark
            @operation change-password
            @entity User
            @param request RequestChangePassword
            @return ResponseChangePassword
            */
            app.MapPost("api/change/password", async ([FromBody] RequestChangePassword request, IRequestHandler<RequestChangePassword, ResponseChangePassword> handler) =>
            {
                var result = await handler.Handle(request, new CancellationToken());
                return Results.Ok(result);
            });
            #endregion
        }

    }
}`
}

function generateBuilderExtension(model: Model): string {
    return expandToString`
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using ${model.configuration?.name}.Domain.Security.Account;
using System.Text;

namespace ${model.configuration?.name}.WebApi.Extensions
{
    /*
     @generated by leds-tools-spark
     @layer configuration
     @entity Security
     */
    public static class BuilderExtension
    {

        // Retrieval of Private Keys defined in appsettings.json
        /*
        @generated by leds-tools-spark
        @operation load-secrets
        @entity Security
        */
        public async static void AddConfiguration(this WebApplicationBuilder builder)
        {
            bool prod = false;

            if (prod)
            {
                Configuration.Secrets.ApiKey = Environment.GetEnvironmentVariable("ApiKey");
                Configuration.Secrets.JwtPrivateKey = Environment.GetEnvironmentVariable("JwtPrivateKey");
                Configuration.Secrets.PasswordSaltKey = Environment.GetEnvironmentVariable("PasswordSaltKey");

                Configuration.Email.DefaultFromEmail = Environment.GetEnvironmentVariable("DefaultFromEmail");
                Configuration.Email.ApiKey = Environment.GetEnvironmentVariable("EmailApiKey");
            }
            else
            {
                Configuration.Secrets.ApiKey = Environment.GetEnvironmentVariable("ApiKey");
                Configuration.Secrets.JwtPrivateKey = Environment.GetEnvironmentVariable("JwtPrivateKey");
                Configuration.Secrets.PasswordSaltKey = Environment.GetEnvironmentVariable("PasswordSaltKey");

                Configuration.Email.DefaultFromEmail = Environment.GetEnvironmentVariable("DefaultFromEmail");
                Configuration.Email.ApiKey = Environment.GetEnvironmentVariable("EmailApiKey");
            }
        }
        // JWT configuration in the API
        /*
        @generated by leds-tools-spark
        @operation configure-jwt
        @entity Security
        */
        public static void AddJwtAuthentication(this WebApplicationBuilder builder)
        {
            builder.Services
                .AddAuthentication(x =>
                {
                    x.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                }).AddJwtBearer(x =>
                {
                    x.RequireHttpsMetadata = false;
                    x.SaveToken = true;
                    x.TokenValidationParameters = new TokenValidationParameters
                    {
                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(Configuration.Secrets.JwtPrivateKey)),
                        ValidateIssuer = false,
                        ValidateAudience = false
                    };
                });
            builder.Services.AddAuthorization();
        }
    }
}`
}

function generateClaimsPrincipalExtension(model: Model): string {
    return expandToString`
using System.Security.Claims;

namespace ${model.configuration?.name}.WebApi.Extensions
{
    /*
     @generated by leds-tools-spark
     @layer extension
     @entity Claims
     */
    public static class ClaimsPrincipalExtension
    {
        /*
         @generated by leds-tools-spark
         @operation get-user-id
         @entity Claims
         @return string
         */
        public static string Id(this ClaimsPrincipal user)
        => user.Claims.FirstOrDefault(c => c.Type == "Id")?.Value ?? string.Empty;

        /*
         @generated by leds-tools-spark
         @operation get-user-name
         @entity Claims
         @return string
         */
        public static string Name(this ClaimsPrincipal user)
            => user.Claims.FirstOrDefault(c => c.Type == ClaimTypes.GivenName)?.Value ?? string.Empty;

        /*        
         @generated by leds-tools-spark
         @operation get-user-email
         @entity Claims
         @return string
         */
        public static string Email(this ClaimsPrincipal user)
            => user.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value ?? string.Empty;
    }
}`
}

function generateJwtExtension(model: Model): string {
    return expandToString`
using Microsoft.IdentityModel.Tokens;
using ${model.configuration?.name}.Application.Security.Account.UseCases.Authenticate;
using ${model.configuration?.name}.Domain.Security.Account;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace ${model.configuration?.name}.WebApi.Extensions
{
     /*
    @generated by leds-tools-spark
    @layer security
    @entity Jwt
     */
    public static class JwtExtension
    {
        /*
        @generated by leds-tools-spark
        @operation generate-jwt
        @entity Jwt
        @param data ResponseData
        @return string
        */
        public static string Generate(ResponseData data)
        {
            var handler = new JwtSecurityTokenHandler();
            var key = Encoding.ASCII.GetBytes(Configuration.Secrets.JwtPrivateKey);
            var credentials = new SigningCredentials(
                new SymmetricSecurityKey(key),
                SecurityAlgorithms.HmacSha256Signature);

            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = GenerateClaims(data),
                Expires = DateTime.UtcNow.AddHours(2),
                SigningCredentials = credentials,
            };
            var token = handler.CreateToken(tokenDescriptor);
            return handler.WriteToken(token);
        }
        
        /*
        @generated by leds-tools-spark
        @operation generate-claims
        @entity Jwt
        @param user ResponseData
        @return ClaimsIdentity
         */

        private static ClaimsIdentity GenerateClaims(ResponseData user)
        {
            var ci = new ClaimsIdentity();
            ci.AddClaim(new Claim("Id", user.Id.ToString()));
            ci.AddClaim(new Claim(ClaimTypes.GivenName, user.Name));
            ci.AddClaim(new Claim(ClaimTypes.Name, user.Email));
            foreach (var role in user.Roles)
                ci.AddClaim(new Claim(ClaimTypes.Role, role));

            return ci;
        }

        /*
        @generated by leds-tools-spark
        @operation generate-refresh-token
        @entity Jwt
        @return Guid
        */
        public static Guid GenerateRefreshToken()
        {
            return Guid.NewGuid();
        }
    }
}`
}

function generateCorsPolicyExtension(model: Model): string {
    return expandToString`
﻿namespace ${model.configuration?.name}.WebApi.Extensions
{
    /*
    @generated by leds-tools-spark
    @layer configuration
    @entity Cors
    */

    
    public static class CorsPolicyExtension
    {
        /*
         @generated by leds-tools-spark
         @operation configure-cors
         @entity Cors
         */
        public static void ConfigureCorsPolicy(this IServiceCollection services)
        {
            services.AddCors(opt =>
            {
                opt.AddDefaultPolicy(builder => builder
                    .AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader());
            });
        }
    }
}
`
}