import { Module, capitalizeString, base_ident } from "../../../../models/model.js";

const ident = base_ident;

export function generateAppsComments(m: Module): string {
    const lines = [
        `from django.apps import AppConfig`,
        `# from django.utils.translation import gettext_lazy as _`,
        ``,
        `class ${capitalizeString(m.name)}Config(AppConfig):`,
        //comentário
        `${ident}"""`,
        `${ident}@generated by leds-tools-spark`,
        `${ident}@layer app config`,
        `${ident}@entity ${m.name}`,
        `${ident}"""`,
        ``,
        `${ident}name  = 'apps.${m.name.toLowerCase()}'`,
        `${ident}label = 'apps_${m.name.toLowerCase()}'`,
         //comentário
        ``,
        `${ident}def ready(self):`,
        `${ident}${ident}"""`,
        `${ident}${ident}@generated by leds-tools-spark`,
        `${ident}${ident}@layer app config`,
        `${ident}${ident}@entity ${m.name}`,
        `${ident}${ident}@operation load-signals`,
        `${ident}${ident}"""`,
        ``,
        `${ident}${ident}import apps.${m.name.toLowerCase()}.signals`,
        ``,
    ];

    return lines.join('\n');
}
