import { base_ident } from "../../../../models/model.js";

const ident = base_ident;

export function generatePaginationComments(): string {
    //comentário
    const headerComment =[

        ``,
        `"""`,
        `@generated by leds-tools-spark`,
        `@layer controller`,
        `@entity CustomPagination`,
        `"""`,
		``,
    ]  
	const lines = [
		`from rest_framework import pagination`,
		`from rest_framework.response import Response`,
        ...headerComment,
        ``,
		`class CustomPagination(pagination.PageNumberPagination):`,
        //comentário
        ``,
        `${ident}"""`,
        `${ident}@generated by leds-tools-spark`,
        `${ident}@layer controller`,
        `${ident}@entity CustomPagination`,
        `${ident}"""`,
        ``,

		`${ident}page_size = 10`,
		`${ident}page_size_query_param = 'page_size'`,
		`${ident}max_page_size = 1000`,
		``,
		`${ident}def get_paginated_response(self, data):`,
        //comentário
        `${ident}${ident}"""`,
        `${ident}${ident}@generated by leds-tools-spark`,
        `${ident}${ident}@layer controller`,
        `${ident}${ident}@entity CustomPagination`,
        `${ident}${ident}operation get_paginated_response`,
        `${ident}${ident}@param data list`,
        `${ident}${ident}@return Response`,
        `${ident}${ident}"""`,
        ``,

		`${ident}${ident}return Response({`,
		`${ident}${ident}${ident}'meta': {`,
		`${ident}${ident}${ident}${ident}'current_page': self.page.number,`,
		`${ident}${ident}${ident}${ident}'per_page': self.page.paginator.per_page,`,
		`${ident}${ident}${ident}${ident}'max_per_page': self.max_page_size,`,
		`${ident}${ident}${ident}${ident}'total': self.page.paginator.count`,
		`${ident}${ident}${ident}},`,
		`${ident}${ident}${ident}'data': data`,
		`${ident}${ident}})`,
		``
	];
	return lines.join('\n');
}
