import { Attribute, Entity, LocalEntity, Model, Module, isLocalEntity, isModule, Actor, base_ident, capitalizeString, createPath } from '../../../../models/model.js'
import { expandToString } from '../../../../../util/template-string.js'

const ident = base_ident;

export function generateSignals(m: Module, map: Map<Entity, Actor>) : string {
    const non_abstract_entities = m.elements.filter(isLocalEntity).filter(e => !e.is_abstract)
    //comentario
    const headerComment = [
        `"""`,
        `@generated by leds-tools-spark`,
        `@layer application`,
        `"""`,
        ``,
    ]
    const lines = [
        `from .models import ${non_abstract_entities.map(e => e.name).join(', ')}`,
        `from django.db.models.signals import (`,
        `${ident}pre_init,   post_init,`,
        `${ident}pre_save,   post_save,`,
        `${ident}pre_delete, post_delete,`,
        `${ident}m2m_changed`,
        `)`,
        `from django.dispatch import receiver`,
        `from django.contrib.auth.models import Group`,
        // `from .services import *`,
        ``,
        ...headerComment,
        ...non_abstract_entities.flatMap(e => {return [
            `## Signals from ${e.name}`,
            entitySignals(e, map),
            ``,
        ]}),
    ]

    return lines.join('\n')
}

function entitySignals(e: LocalEntity, map: Map<Entity, Actor>) : string {
    const post_save = map.has(e) ?
        expandToString`
            if created:
                group = Group.objects.get(name="${map.get(e)?.id}")
                instance.user_application.groups.add(group)
        ` :
        'pass'

    return expandToString`
        @receiver(pre_init, sender=${e.name})
        def pre_init_${e.name.toLowerCase()}(sender, *args, **kwargs):
        
        ${ident}"""
        ${ident}@generated by leds-tools-spark
        ${ident}@layer application
        ${ident}@entity ${e.name}
        ${ident}@operation pre-init
        ${ident}"""

        ${ident}pass

        @receiver(post_init, sender=${e.name})
        def post_init_${e.name.toLowerCase()}(sender, instance, **kwargs):

        ${ident}"""
        ${ident}@generated by leds-tools-spark
        ${ident}@layer application  
        ${ident}@entity ${e.name}
        ${ident}@operation post-init
        ${ident}"""

        ${ident}pass

        @receiver(pre_save, sender=${e.name})
        def pre_save_${e.name.toLowerCase()}(sender, instance, raw, using, update_fields, **kwargs):

        ${ident}"""
        ${ident}@generated by leds-tools-spark
        ${ident}@layer application
        ${ident}@entity ${e.name}
        ${ident}@operation pre-save
        ${ident}@param instance: ${e.name}
        ${ident}"""

        ${ident}pass

        @receiver(post_save, sender=${e.name})
        def post_save_${e.name.toLowerCase()}(sender, instance, created, raw, using, update_fields, **kwargs):

        ${ident}"""
        ${ident}@generated by leds-tools-spark
        ${ident}@layer application
        ${ident}@entity ${e.name}
        ${ident}@operation post-save
        ${ident}@param instance: ${e.name}
        ${ident}"""

        ${ident}${post_save}

        @receiver(pre_delete, sender=${e.name})
        def pre_delete_${e.name.toLowerCase()}(sender, instance, using, **kwargs):

        ${ident}"""
        ${ident}@generated by leds-tools-spark
        ${ident}@layer application
        ${ident}@entity ${e.name}
        ${ident}@operation pre-delete
        ${ident}"""

        ${ident}pass

        @receiver(post_delete, sender=${e.name})
        def post_delete_${e.name.toLowerCase()}(sender, instance, using, **kwargs):

        ${ident}"""
        ${ident}@generated by leds-tools-spark
        ${ident}@layer application
        ${ident}@entity ${e.name}
        ${ident}@operation post-delete
        ${ident}"""

        ${ident}pass

        @receiver(m2m_changed, sender=${e.name})
        def m2m_changed_${e.name.toLowerCase()}(sender, instance, action, reverse, model, pk_set, using, **kwargs):

        ${ident}"""
        ${ident}@generated by leds-tools-spark
        ${ident}@layer application
        ${ident}@entity ${e.name}
        ${ident}@operation m2m-changed
        ${ident}@param action: str — Type of M2M modificatio
        ${ident}"""

        ${ident}pass
    `
}
