import { LocalEntity, Module, isLocalEntity, base_ident } from "../../../../models/model.js";

const ident = base_ident

function generateURLAPIAux(e: LocalEntity) : string {
    return `router.register(r'${e.name.toLowerCase()}', ${e.name}ViewSet, basename='${e.name.toLowerCase()}')`
}

export function generateURLAPI(m: Module) : string {
    const entities = m.elements.filter(isLocalEntity).filter(e => !e.is_abstract)

    const headerComment =[
        ``,
        `"""`,
        `@generated by leds-tools-spark`,
        `@layer view`,
        `"""`,
        ``
    ]

    const lines = [
        `from django.urls import path, register_converter, include`,
        `from rest_framework import routers`,
        `from .api_views import (`,
        ...entities.map(e =>
            `${ident}${e.name}ViewSet,`
        ),
        `)`,
         ...headerComment,
        `router = routers.DefaultRouter()`,
        ``,
        `#@generated by leds-tools-spark`,
        `#Automatic routing of entities`,
        ...entities.map(e => generateURLAPIAux(e)),
        ``,
        `urlpatterns = [`,
        `${ident}path('${m.name.toLowerCase()}/', include(router.urls))`,
        `]`,
        ``
    ]

    return lines.join('\n')
}
