import { base_ident } from "../../../../models/model.js";

const ident = base_ident;

export function generateUtil(): string {
    const lines = [
        `from hashids import Hashids`,
        `from django.conf import settings`,
        ``,
        `hashids = Hashids(settings.HASHIDS_SALT, min_length=8)`,
        ``,
        `def h_encode(id):`,

        //comentário
        `${ident}"""`,
        `${ident}@generated by leds-tools-spark`,
        `${ident}@operation encode`,
        `${ident}@param id: int — Numeric ID to be encoded.`,
        `${ident}@return str — Corresponding encoded hash.,`,
        `${ident}"""`,
        ``,

        `${ident}return hashids.encode(id)`,
        ``,
        `def h_decode(h):`,

        //comentário
        `${ident}"""`,
        `${ident}@generated by leds-tools-spark`,
        `${ident}@operation decode.`,
        `${ident}@param h: str — Hash to be decoded.`,
        `${ident}@return int | None — Decoded ID or None if invalid.`,
        `${ident}"""`,
        ``,

        `${ident}if z := hashids.decode(h):`,
        `${ident}${ident}return z[0]`,
        ``,

        `class HashIdConverter:`,

        //comentário
        `${ident}"""`,
        `${ident}@generated by leds-tools-spark`,
        `${ident}@layer application`,
        `${ident}@operation url-converter`,
         `${ident}"""`,

        `${ident}regex = '[a-zA-Z0-9]{8,}'`,
        ``,

        `${ident}def to_python(self, value):`,

        //comentário
        `${ident}${ident}"""`,
        `${ident}${ident}@generated by leds-tools-spark`,
        `${ident}${ident}@layer application`,
        `${ident}${ident}@operation to_python`,
        `${ident}${ident}@param value: str — Hash received from the URL`,
        `${ident}${ident}@return int | None — Corresponding numeric ID`,
        `${ident}${ident}"""`,
        `${ident}${ident}return h_decode(value)`,
        ``,


        `${ident}def to_url(self, value):`,

        //comentário
        `${ident}${ident}"""`,
        `${ident}${ident}@generated by leds-tools-spark`,
        `${ident}${ident}@layer application`,
        `${ident}${ident}@operation to_url`,
        `${ident}${ident}@param value: int — Numeric ID to be converted to hash`,
        `${ident}${ident}@return str — Corresponding hash for the URL`,
        `${ident}${ident}"""`,

        `${ident}${ident}return h_encode(value)`,
        ``
    ];

    return lines.join("\n");
}
