import { expandToString, LocalEntity, Model, isLocalEntity, isModule } from "../../../../models/model.js"
import fs from "fs";
import path from "path";
import {getEntityName} from "../../../../../util/generator-utils.js";
export function generate(model: Model, target_folder: string) : void {

    const entities_folder = target_folder + '/Entities'

    fs.mkdirSync(entities_folder, {recursive: true})
    
    fs.writeFileSync(path.join(target_folder,`IBaseService.cs`), generateBaseService(model))

    const modules =  model.abstractElements.filter(isModule);

    for(const mod of modules) {
        const mod_classes = mod.elements.filter(isLocalEntity)
        for(const cls of mod_classes) {
            fs.writeFileSync(path.join(entities_folder,`I${cls.name}Service.cs`), generateService(model, cls))
        }
    }
}

function generateBaseService (model: Model): string {
    return expandToString`
﻿using ${model.configuration?.name}.Application.DTOs.Common;

namespace ${model.configuration?.name}.Application.Interfaces
{
    /**
     * @generated by leds-tools-spark
     * @layer service
     * @entity BaseService
     */

    public interface IBaseService<Request, Response, Entity>
    {
         /**
         * @generated by leds-tools-spark
         * @operation getAll
         * @return IQueryable<Response>
         */
        Task<IQueryable<Response>> GetAll();
        /**
         * @generated by leds-tools-spark
         * @operation getById
         * @param id Guid
         * @return IQueryable<Response>
         */
        Task<IQueryable<Response>> GetById(Guid id);
        /**
         * @generated by leds-tools-spark
         * @operation create
         * @param request Request
         * @param cancellationToken CancellationToken
         * @return ApiResponse
         */
        Task<ApiResponse> Create(Request request, CancellationToken cancellationToken);
        /**
         * @generated by leds-tools-spark
         * @operation delete
         * @param id Guid
         * @param cancellationToken CancellationToken
         * @return ApiResponse
         */
        Task<ApiResponse> Delete(Guid id, CancellationToken cancellationToken);
        /**
         * @generated by leds-tools-spark
         * @operation update
         * @param request Request
         * @param cancellationToken CancellationToken
         * @return ApiResponse
         */ 
        Task<ApiResponse> Update(Request request, CancellationToken cancellationToken);
        /**
         * @generated by leds-tools-spark
         * @operation saveValidation
         * @return List<string>
         */
        abstract List<string> SaveValidation();

    }
}
`
}

function generateService(model: Model, cls: LocalEntity) : string {
    return expandToString`
using ${model.configuration?.name}.Application.DTOs.Entities.Request;
using ${model.configuration?.name}.Application.DTOs.Entities.Response;
using ${model.configuration?.name}.Domain.Entities;

namespace ${model.configuration?.name}.Application.Interfaces.Entities
{
    /*
     * @generated by leds-tools-spark
     * @layer service
     * @entity ${cls.name}
     */
    public interface I${cls.name}Service : IBaseService<${cls.name}RequestDTO, ${cls.name}ResponseDTO, ${cls.name}>
    {
    }
}

`
}