import { expandToStringWithNL, Model }from "../../../../../../models/model.js"
import fs from "fs";
import path from "path";

export function generate(model: Model, target_folder: string): void {
    fs.writeFileSync(path.join(target_folder, `StringExtension.cs`), generateExtension(model));
}

function generateExtension(model: Model): string {
    return expandToStringWithNL`
using System.Text;

namespace ${model.configuration?.name}.Domain.Security.Shared.Extensions
{
    /*
    @generated by leds-tools-spark
    @layer model
    @entity StringExtension
    */
    public static class StringExtension
    {
        /*@generated by leds-tools-spark
        @operation to-base64
        @entity StringExtension
        @param text string
        @return string
        */
        public static string ToBase64(this string text) => Convert.ToBase64String(Encoding.ASCII.GetBytes(text));
    }
}`;
}