name: Bump Version and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Configurar Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Instalar dependências
        run: |
          npm ci

      - name: Build do projeto
        run: npm run build && npx tsc

      - name: Análise com SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

          
      - name: Bump de versão (minor)
        id: package_version
        run: |
          VERSION=$(npm version minor -m "ci: release %s [skip ci]") # Removido o '|' extra e indentado corretamente
          echo "version=$VERSION" >> $GITHUB_OUTPUT    

      - name: Publicar no NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tag e versionamento para o GitHub
        run: |
          git push origin main --follow-tags

      - name: Apagar tags antigas
        run: |
          # Obtém a tag mais recente (a última criada)
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)

          echo "Mantendo a tag mais recente: $latest_tag"

          # Lista todas as tags, exclui a mais recente e deleta as demais
          for tag in $(git tag); do
            if [ "$tag" != "$latest_tag" ]; then
              git push --delete origin "$tag"
              git tag -d "$tag"
              echo "Tag apagada: $tag"
            fi
          done

      - name : Enviar email de notificação
        uses:  dawidd6/action-send-mail@v3
        with: 
              server_address: smtp.gmail.com
              server_port: 465
              secure: true
              username: ${{ secrets.EMAIL_USER }}
              password: ${{ secrets.EMAIL_PASS }}
              subject: "📦 Novo pacote publicado: v${{ steps.package_version.outputs.version }}"
              body: |
                ✅ Publicação concluída com sucesso!
        
                📁 Repositório: ${{ github.repository }}
                🔖 Versão: v${{ steps.package_version.outputs.version }}              
                📦 NPM: https://www.npmjs.com/package/spark-generators-lib
              to: caiochiabaioliveira@gmail.com, diegobrangel8@gmail.com, valentimcaldeira100@gmail.com, Lucas.codeco2@gmail.com, brunoowcx1@gmail.com
              from: GitHub Actions <${{ secrets.EMAIL_USER }}>
