import { expandToStringWithNL, Model }from "../../../../models/model.js"
import fs from "fs"
import path from "path";

export function generate(model: Model, target_folder: string) : void {

    fs.writeFileSync(path.join(target_folder,`DomainExceptionValidation.cs`), generateDomainException(model))
}

function generateDomainException(model: Model): string {
    return expandToStringWithNL`
namespace ${model.configuration?.name}.Domain.Validation
{
    /*
    @generated by leds-tools-spark
    @layer domain
    @entity DomainValidationException
    */
    public class DomainValidationException : Exception
    {
        public List<string> Errors { get; }

        /*@generated by leds-tools-spark
        @operation constructor
        @entity DomainValidationException
        @param validationsErrors List<string>
        */
        public DomainValidationException(List<string> validationsErrors)
        {
            Errors = validationsErrors;
        }

        /*@generated by leds-tools-spark
        @operation to-string
        @entity DomainValidationException
        @return string
        */
        public override string ToString()
        {
            return string.Join(Environment.NewLine, Errors);
        }
    }
}`
}